# based on
# - a template offered by the github action wizard,
# - the testing-on-MR script next to this file
# - consulting with collegues (thx to @Pfnei)
# - the documentation at https://github.com/actions/download-artifact
# - documentation provided by the intelliJ IDE

name: Create and Deposit Jar Artefact

on:
  release:
    types: [created] # note: attaching to upload would require extra steps and decisions TODO?
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR artifact - attach to CI-Run
      uses: actions/upload-artifact@v4
      with:
        name: 'slm-tic-tac-toe-nightly.jar'
        overwrite: true
        compression-level: '0'
        retention-days: '3'
        path: target/slm-tic-tac-toe-nightly.jar

    - name: Release JAR to GitHub
      uses: softprops/action-gh-release@v2
      if: github.event_name == 'release'
      with:
        files: target/slm-tic-tac-toe-nightly.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}